### ISSUE TITLE
Build metadata should not be used when determining precedence

### ISSUE THREAD

**Issue by smumriak** [SwiftPackageIndex/SemanticVersion#14]
Bullet point 10 in SemVer specification states

> Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85, 1.0.0+21AF26D3----117B344092BD.

**Comment by finestructure** [comment]
Thanks for the bug report, @smumriak. This is being addressed here: #11

**Comment by daveverwer** [comment]
Looks like this didn't get closed. Cleaning up now!
